
bot.tooltip.new_feed=New Feed
bot.tooltip.edit_feed=Edit Feed
bot.tooltip.remove_feed=Remove Feed

bot.heading.clear_feed_cache=Clear feed cache
bot.label.every=Every
bot.label.hours=hours
bot.label.at=at
bot.label.minutes_past=minutes past the hour.
bot.label.minutes=minutes.
bot.label.title=Title:
bot.label.keyword=Keyword:
bot.label.url=URL:
bot.label.rss_type=RSS Type:

bot.message.confirm_remove=Remove feed "{0}"?
bot.message.required_fields=The title, keyword, and url fields are required.
bot.message.keyword_invalid=The keyword must start with a letter and may contain only letters, numbers, and hyphens.
bot.message.url_invalid=Please enter a valid URL.

bot.window.title.feed_details=RSS Feed Details
bot.window.comment.feed_details=RSS Feed Details

